xsetroot -xcf /usr/share/icons/Vimix-cursors-white/cursors/left_ptr 28
xrandr &&
xrandr --output eDP1 --scale-from 1920x1080
setbg &
pipewire &
xrdb "${XDG_CONFIG_HOME:-$HOME/.config}"/X11/xresources
remaps &
cleanup &
sxhkd &
exec bspwm
