#!/bin/sh

killall wired
wired -r &

killall ibus-daemon
ibus-daemon -dx
~/.config/polybar/launch.sh --shades &
# picom --experimental-backends &
copyq &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         2
bspc config window_gap          12
bspc config focused_border_color \#1FBED6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
